// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6lDh9HeNzAfxeZRDbn9sS29XI35TXX8',
    appId: '1:953787862084:web:23aeafa71fd9002a5e4011',
    messagingSenderId: '953787862084',
    projectId: 'gdsc-dms',
    authDomain: 'gdsc-dms.firebaseapp.com',
    storageBucket: 'gdsc-dms.appspot.com',
    measurementId: 'G-7JW71HWHS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP2aU8YzGtgK7P4wJ5c-M7h1mI9Y9F7-8',
    appId: '1:953787862084:android:48e0fe1a61af77b25e4011',
    messagingSenderId: '953787862084',
    projectId: 'gdsc-dms',
    storageBucket: 'gdsc-dms.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6lDh9HeNzAfxeZRDbn9sS29XI35TXX8',
    appId: '1:953787862084:web:20171eeff879d1905e4011',
    messagingSenderId: '953787862084',
    projectId: 'gdsc-dms',
    authDomain: 'gdsc-dms.firebaseapp.com',
    storageBucket: 'gdsc-dms.appspot.com',
    measurementId: 'G-0M2Q8F57MV',
  );
}
